name: Build and Deploy to VM

on:
  push:
    branches:
      - "main"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install nodejs v16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          check-latest: false

      - name: Install Dependencies
        run: |
          npm ci
          npm run build
          ls ./build